on:
  push:
  # schedule:
  # - cron: '30 9 * * 4'

jobs:
  check_attendacy_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Attendee check message
        working-directory: ./src
        run: python schedule.py
